[tool.poetry]
name = "{{cookiecutter.project_slug}}"
version = "{{cookiecutter.version}}"
description = "{{cookiecutter.project_short_description}}"
authors = ["{{cookiecutter.full_name}} <{{cookiecutter.email}}>"]

[tool.poetry.dependencies]
{{cookiecutter.project_slug}} = { path = "./" }
pip = ">=20.1.0"
python = "^3.6"

[tool.poetry.dev-dependencies]
bump2version = ">=0.5.11"
{% if cookiecutter.command_line_interface|lower == 'click' -%}
Click = ">=7.0"
{% endif %}
dlint = ">=0.10.2"
flake8-eradicate = ">=0.3.0"
importmagic3 = ">=0.2.0"
pip = ">=20.1.0"
py-make = ">=0.1.1"
{% if cookiecutter.use_pytest == 'y' -%}
pytest = ">=5.4.1"
pytest-cov = ">=2.8.1"
pytest-mock = ">=3.1.0"
{% endif %}
python-language-server = {extras = ["all"],version = ">=0.31.10"}
pyls-mypy = ">=0.1.8"
Sphinx = ">=1.8.5"
tox = ">=3.14.6"
tox-pipenv = ">=1.9.0"
twine = ">=1.14.0"
watchdog = ">=0.9.0"
wheel = ">=0.33.6"


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
