[tool.poetry]
name = "{{cookiecutter.project_slug}}"
version = "{{cookiecutter.version}}"
description = "{{cookiecutter.project_short_description}}"
authors = ["{{cookiecutter.full_name}} <{{cookiecutter.email}}>"]

[tool.poetry.dependencies]
pip = ">=20.1.0"
python = "^3.6"

[tool.poetry.dev-dependencies]
bump2version = ">=0.5.11"
{% if cookiecutter.command_line_interface|lower == 'click' -%}
Click = ">=7.0"
{% endif %}
pip = ">=20.1.0"
py-make = ">=0.1.1"
{% if cookiecutter.use_pytest == 'y' -%}
pytest = ">=5.4.1"
pytest-cov = ">=2.8.1"
pytest-mock = ">=3.1.0"
{% endif %}
Sphinx = ">=1.8.5"
tox = ">=3.14.6"
watchdog = ">=0.9.0"
whell = ">=0.34.2"
black = "*"
importmagic3 = "*"
monkeytype = "*"
mypy = "*"
pylint = "*"
wemake-python-styleguide = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
